export const apiErrorCodes = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  CUSTOMER_NOT_FOUND: "CUSTOMER_NOT_FOUND",
  INVALID_ID_FORMAT: "INVALID_ID_FORMAT",
  ERROR_FETCHING_CUSTOMER: "ERROR_FETCHING_CUSTOMER",
  ERROR_UPDATING_CUSTOMER: "ERROR_UPDATING_CUSTOMER",
} as const;
